### ISSUE TITLE
[Feature Request] Enter Key to confirm

### ISSUE THREAD

**Issue by LootFever** [outlying/ItemSplitter#15]
Hey,

first of all I wnted to say thanks for having the addon auto focus the edit box.
Was thinking of making the request today but now I won't have to.

But one thing that I find missing now that it's added, is using the enter key to confirm.
Or in other words pressing enter should work like the Split button.
So that after entering a number u can hit a quick enter to split the stack.

Maybe have a Shift-Enter work as the Auto Split button to complete the functionality.

**Comment by outlying** [comment]
Thanks for using GitHub, at least I'm getting good notifications here about issues. I'll verify it and if I can confirm it I'll add support for enter key, I'll let you know about progress here, it shouldn't be problematic to code.

**Comment by outlying** [comment]
@LootFever try version `0.1.10` and let me know if that's OK

**Comment by LootFever** [comment]
Looks good to me. Even though I'm not a fan of the Alt-click but thats just personal preference.

**Comment by outlying** [comment]
What do you mean by alt click? Enter should work for split

niedz., 8 wrz 2024, 19:26 użytkownik LootFever ***@***.***>
napisał:
